[package]
name = "ctfbox"
version = "0.1.0"
description = "CTFBox desktop workbench"
authors = ["ZBHD"]
edition = "2021"

[lib]
name = "ctfbox_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "=2.5.4"
tauri-plugin-process = "=2.3.1"
tauri-plugin-updater = "=2.10.1"

[dev-dependencies]
minisign-verify = "=0.2.5"
